import './Terms.css'
import React, { Component } from 'react'
import { withRouter, NavLink } from 'react-router-dom'


class Terms extends Component {

    componentDidMount() {
        window.scrollTo({ top: 0, behavior: 'smooth' })
    }
    
    render() {
        return (<div><div className="container terms-container">
            <h2 className="terms-title">TERMS OF USE OF AUCTUS' WEBSITE / PLATFORM</h2>
            <p>Last updated: Mar 24, 2020</p>
            <p>Welcome to app.auctus.org, a website of AUCTUS PROJECT INC, a company incorporated under the laws of British Virgin Islands ("<b>Auctus</b>", "<b>we</b>", "<b>our</b>", "<b>The Company</b>").</p>
            <p>Please read carefully these Terms of Use (hereinafter – the "<b>Terms</b>", "<b>Terms of Use</b>") as they affect your obligations and legal rights, including, but not limited to waivers of rights and limitation of liability. If you do not agree to such terms you must stop using this website and any information, links or content contained on this website. Your access to, registration at and use of this platform constitutes your acceptance of and agreement to be bound by each of the terms set forth below, including our <NavLink to="/privacy">Privacy Policy</NavLink>, which is hereby incorporated in these Terms by reference. By accessing or using this Website you represent and warrant that you have the right, authority and capacity to enter into this Terms and to be abide by all of the terms contained herein. If you are using our Website on behalf of your organization, that organization accepts these terms. If you want to withdraw this consent, you have to cease using the Website.</p>
            <p>Auctus provides access to a decentralized money saving tool (“Platform”) on the Ethereum blockchain, that allows participants to use Ethereum assets (“Assets”) to transact using smart contracts (“Smart Contracts”).</p>
            <p>THE SITE IS AN ADMINISTRATIVE PLATFORM ONLY. WE ARE NOT A BROKER, DEALER, FINANCIAL INSTITUTION, EXCHANGE, CUSTODIAN, ROBO-ADVISOR, INTERMEDIARY, OR CREDITOR. THE SITE DOES NOT FACILITATE TRANSACTIONS BETWEEN BUYERS AND SELLERS, INCLUDING WITH RESPECT TO ANY TRANSACTIONS THAT OCCUR DURING A REBALANCE, WHICH TRANSACTIONS OCCUR ON THIRD-PARTY, UNAFFILIATED PLATFORMS. THE COMPANY IS NOT A COUNTERPARTY TO ANY TRANSACTION ON THE SITE OR FOR ANY USER OF THE SITE. NEITHER THE SITE NOR THE COMPANY PROVIDES FINANCIAL ADVISORY, LEGAL, REGULATORY, OR TAX SERVICES DIRECTLY, INDIRECTLY, IMPLICITLY, OR IN ANY OTHER MANNER, AND YOU SHOULD NOT CONSIDER ANY CONTENT CONTAINED IN THIS AGREEMENT OR OTHERWISE POSTED ON THE SITE TO BE A SUBSTITUTE FOR PROFESSIONAL FINANCIAL, LEGAL, REGULATORY, TAX OR OTHER ADVICE</p>
            <p>THIS WEBSITE, INFORMATION AND CONTENT AVAILABLE ON IT IS NOT INTENDED TO CONSTITUTE AN OFFER OF SECURITIES OR A SOLICITATION FOR INVESTMENT IN SECURITIES IN ANY JURISDICTION, NOR IS IT INTENDED TO CONSTITUTE A PROSPECTUS OR OFFER DOCUMENT OF ANY SORT. WE DO NOT PROVIDE ANY OPINION OR ANY ADVICE TO PURCHASE, SELL, OR OTHERWISE TRANSACT WITH AUC TOKENS AND THE PRESENTATION, PUBLICATION OR COMMUNICATION OF ALL OR ANY PART OF THE INFORMATION IN THE WHITEPAPER OR ON THE WEBSITE SHALL NOT FORM THE BASIS OF, OR BE RELIED UPON IN CONNECTION WITH, ANY CONTRACT OR INVESTMENT DECISION. PLEASE CONSULT YOUR OWN LEGAL OR FINANCIAL ADVISOR.</p>
            <h3>ELECTRONIC ENLIGHTENMENTS</h3>
            <p>Visiting the Website, using any contact form on the Site or sending emails to it constitutes electronic notices. You agree and consent to receive electronically all communications, agreements, documents, receipts, notices and disclosures (collectively, "<b>Communications</b>") that Auctus provides in connection with your use of the Site. You agree that Auctus may provide these Communications to you by posting them on the Website, by emailing them to you at the email address you provide, and/or by sending an SMS or text message to a mobile phone number that you provide; any such Communication shall be valid and have legal force.</p>
            <h3>1. ASSUMPTION OF RISK</h3>
            <b>
                <p>You acknowledge that the Site (including without limitation the Platform and the Smart Contracts) and your use of the Site contain certain risks, including without limitation the following risks: That any Smart Contracts you interact with are entirely your own responsibility / liability, and Auctus is not a party to the Smart Contracts;At any time, your access to your Assets may be suspended or terminated or there may be a delay in your access or use of your Assets which may result in the Assets diminishing in value or you being unable to complete a Smart Contract and the Protocol may be suspended or terminated for any or no reason, which may limit your access to your Assets.</p>
                <p>Accordingly, you expressly agree that: (A) you assume all risk in connection with your access and use of the Site, the Protocol and the Smart Contracts; and (B) that you expressly waive and release Auctus from any and all liability, claims, causes of action, or damages arising from or in any way related to your use of the Site, the Protocol or the Smart Contracts.</p>
            </b>
            <h3>2. FEEDBACK</h3>
            <p>You may contact us by either (a) filling out and completing a contact form, which may be from time to time available at the Website, or by (b) contacting us directly by email to the address: <a href="mailto:contact@auctus.org" rel="noopener noreferrer" target="_blank">contact@auctus.org</a>. The contact form on the Website may require, inter alia, your full name, e-mail address, phone number, country of residence, company/organization name, your position in the company/organization.</p>
            <h3>3. MINORS</h3>
            <p>The Site is intended for persons over the age of eighteen (18), no part of the Website may be used or accessed by the Users under this age. By using or accessing the Website you represent that you are at least 18 years old. We reserve the right to request proof of age at any stage so that we can verify that minors under this age are not using the Site. In the event that it comes to our knowledge that a person under the age of eighteen (18) is using the Site, or if a person refuses to provide proof of age, we will prohibit and block such User from accessing the Site and will make all efforts to promptly delete any Personal Information (as such term is defined in our Privacy Policy) with regard to such User.</p>
            <p>Certain countries may define different age restrictions. You are solely responsible for complying with the regulations and laws of the territory from which you access or use the Website.</p>
            <h3>4. THIRD-PARTY CONTENT</h3>
            <p>In using our Site, you may view certain content provided by third parties, including, inter alia, advertisements, promotions, materials and links to third-party resources or websites (the "<b>Third-party content</b>"). Auctus is not responsible for and does not make any warranties as to the Third party content, does not endorse and is not responsible for any information, statements, content, ads, goods or services, or other materials on or available from such resources or websites. </p>
            <p>We are not responsible or liable for any loss or damage of any sort incurred as the result of accessing or using of any Third-party content, and you understand that your use of Third-party content, and your interactions with third parties that are linked to or from our Website, is at your own risk.</p>
            <h3>5. USER GENERATED CONTENT</h3>
            <p>The Website may provide possibility for posting or creating content through the Website (the "<b>User generated content</b>"). If you create or provide any User generated content, you must ensure that such content at all times is true, accurate, complete and up to date, and that such content does not breach any rights of third parties or laws. By creating or providing any User generated content to the Website you warrant that you own all intellectual property rights to such content, that such content does not violate any rights of third parties, laws or regulations. You shall be solely liable and responsible for your User generated content.</p>
            <p>We do not review all User generated content and do not have such an opportunity. We do not undertake any obligations in respect to the User generated content, e.g. obligations of confidentiality. At all times, we retain the right to remove any User generated content without any prior notice if case we, in our sole discretion, determine that such content is offensive, unacceptable, may harm us or violate these Terms, any laws or public order.</p>
            <p>By creating or providing User generated content to us you grant Auctus, its agents, contractors, partners, officers, employees and successors a non-exclusive, irrevocable, royalty free, perpetual, worldwide right to use, copy, edit, reproduce, translate, publicly display and perform, distribute, create derivative works from your User generated content and the right to assign these rights to third parties in whole or in part.</p>
            <h3>6. NO ADVICE</h3>
            <p>No part of the information or content available on the Website should be considered to be business, legal, financial or tax advice regarding Auctus, AUC tokens, cryptocurrencies or any of the matters to which all or any part of such information relates. You should consult your own legal, financial, tax or other professional advisor regarding this information. You should be aware that you may be required to bear the financial risk of any purchase of cryptocurrencies for an indefinite period of time.</p>
            <p>We shall not be responsible for the accuracy of the information and materials on the Website, therefore any use of such information or materials is at your own discretion and risk and you are solely responsible for any possible damages or losses arising from such use, e.g. damages to your computer system, loss of data.</p>
            <h3>7. USE GUIDELINE</h3>
            <p>You may not use the Website, its content and services provided through the Website for purposes other than those specified by Auctus. You may not use this Website in any manner that could disrupt, interfere with or inhibit other Users from using this Website, or that could disable, impair or harm the functioning of the Website or servers. You may not use the Website to collect any data or information for any purposes other than stated on the Website, e.g. for market or other research for any third parties. You may not use robots, spiders or other automated means to access the Website or its parts, provided, however, that search engines and their operators may use such means for creating publicly-available searchable indices of the materials, excluding caches or archives of such materials.</p>
            <p>You may not use the Website and its content to make any statements that result or could result in perceiving AUC token by other persons and Users as (a) an investment instrument, (b) security, (c) an instrument that could provide any sort of income in future, (d) an instrument that could be used for speculative purposes.</p>
            <h3>8. INTELLECTUAL PROPERTY RIGHTS</h3>
            <p>The Website contains materials and data, e.g. analytics, software, technologies, texts, code, graphics, logos, images provided by or on behalf of Auctus (the “<b>Auctus’ IP</b>”). Such Auctus’ IP may be owned by us or by third parties, is protect under the laws of British Virgin Islands, EU and other countries, and may not be copied, imitated or used, in whole or in part, without our prior written permission. You do not have nor obtain any rights to Auctus’ IP and nothing in this documents grants such rights. Elements of the Website, Auctus etc. are protected as trade dress, trademarks and as other Intellectual Property Rights objects. Unauthorized use of Auctus’ IP may violate our rights and rights of third parties.</p>
            <p>In addition, the look and feel of Auctus, our services, including all page headers, custom graphics, button icons and scripts, is the service mark, trademark and/or trade dress of Auctus (whether registered or not) and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and company names or logos mentioned through the Website are the property of their respective owners.</p>
            <p>Reference to any products, services, processes or other information, by name, trademark, manufacturer, and supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation by us.</p>
            <h3>9. COLLECTION OF INFORMATION</h3>
            <p>Auctus may collect information and statistics collectively about the visitors and Users of the Website, including information that you provide to us, in order to improve the Website. Auctus may share such aggregate information if it is necessary for achieving the above mentioned goals, provided that the processing of personal information is done in accordance with our Privacy Policy.</p>
            <h3>10. AVAILABILITY AND ACCESS</h3>
            <p>Generally, we are not going to terminate access to the Website for any user, the Website is public and can be accessed without login or registration. At the same time, the Website’s availability and functionality depends on various factors, such as communication networks. Auctus does not warrant or guarantee that the Site will operate and/or be available at all times without disruption or interruption, or that it will be immune from unauthorized access or error-free.</p>
            <p>We may terminate these Terms, same as your access to the Website or any of its parts at any time without any prior notice and liability.</p>
            <h3>11. JURISDICTION AND DISPUTE RESOLUTION</h3>
            <p><span className="underline">Governing Law</span>. These Terms will be governed by and construed and enforced in accordance with the laws of British Virgin Islands, without regard to conflict of law rules or principles that would cause the application of the laws of any other jurisdiction. Any Dispute between the Parties arising out or relating to these Terms or its subject matter or formation (including non-contractual Disputes or claims) that is not subject to arbitration shall be exclusively resolved by the courts of British Virgin Islands.</p>
            <p><span className="underline">Binding Arbitration</span>. Except for any disputes, claims, suits, actions, causes of action, demands or proceedings (collectively, “Disputes”) in which either Party seeks injunctive or other equitable relief for the alleged unlawful use of intellectual property, including, without limitation, copyrights, trademarks, trade names, logos, trade secrets or patents, you and the Company (i) waive your and the Company’s respective rights to have any and all Disputes arising from or related to these Terms resolved in a court, and (ii) waive your and the Company’s respective rights to a jury trial. Instead, you and the Company will arbitrate Disputes through the binding arbitration (which is the referral of a Dispute to one or more persons charged with reviewing the Dispute and making a final and binding determination to resolve it instead of having the Dispute decided by a judge or jury in court). Any Dispute shall be referred to and finally resolved by arbitration under the Rules of the London Court of International Arbitration in force on the date on which the arbitration is commenced, which Rules are deemed to be incorporated by reference into these Terms. The seat of the arbitration shall be London, the United Kingdom. The language of the arbitration shall be English. Any award of the tribunal shall be final and binding from the day it is made. The tribunal shall consist of three arbitrators. Each party hereto shall nominate one arbitrator. In the event that either of the two parties hereto fails to nominate an arbitrator within 30 days after the commencement of the arbitration proceedings, then the London Court of International Arbitration shall nominate an arbitrator on behalf of the party or parties hereto which have failed to nominate an arbitrator. The third arbitrator, who shall be the presiding arbitrator, shall be nominated by the two party-nominated arbitrators within 30 days of the last of their appointments. The parties hereto agree to keep confidential all matters relating to the arbitration, including related court proceedings, to the greatest extent practicable.</p>
            <p><span className="underline">No Class Arbitrations</span>. Class Actions or Representative Actions. Any Dispute arising out of or related to these Terms is personal to you and the Company and will be resolved solely through individual arbitration and will not be brought as a class arbitration, class action or any other type of representative proceeding. There will be no class arbitration or arbitration in which an individual attempts to resolve a Dispute as a representative of another individual or group of individuals. Further, a Dispute cannot be brought as a class or other type of representative action, whether within or outside of arbitration, or on behalf of any other individual or group of individuals.</p>
            <p><span className="underline">Notice: Informal Dispute Resolution</span>. Each Party will notify the other Party in writing of any arbitrable or small claims Dispute within thirty (30) days of the date it arises, so that the Parties can attempt in good faith to resolve the Dispute informally. Notice to the Company shall be sent by e-mail to the Company at <a href="mailto:contact@auctus.org" rel="noopener noreferrer" target="_blank">contact@auctus.org</a>. Notice to you shall be sent by email to the email address you provide to us as part of the Whitelisting process. Your notice must include (i) your name, postal address, email address and telephone number, (ii) a description in reasonable detail of the nature or basis of the Dispute, and (iii) the specific relief that you are seeking. If you and the Company cannot agree how to resolve the Dispute within thirty (30) days after the date notice is received by the applicable Party, then either you or the Company may, as appropriate and in accordance with this Section 12, commence an arbitration proceeding or, to the extent specifically provided for in the first paragraph of this Section 12, file a claim in court.</p>
            <p><span className="underline">Authority of Arbitrator</span>. The arbitrator will have (i) the exclusive authority and jurisdiction to make all procedural and substantive decisions regarding a Dispute, including the determination of whether a Dispute is arbitrable, and (ii) the authority to grant any remedy that would otherwise be available in court; provided, however, that the arbitrator does not have the authority to conduct a class arbitration or a representative action, which is prohibited by these Terms. The arbitrator may only conduct an individual arbitration and may not consolidate more than one individual’s claims, preside over any type of class or representative proceeding or preside over any proceeding involving more than one individual.</p>
            <h3>12. LIMITATION OF LIABILITY</h3>
            <p>TO THE MAXIMUM EXTENT LEGALLY PERMISSIBLE, IN NO EVENT SHALL AUCTUS, INCLUDING AUCTUS'S REPRESENTATIVES, OFFICERS, EMPLOYEES, AGENTS, CONTRACTORS, PARTNERS, ASSIGNEES BE LIABLE FOR ANY DAMAGES WHATSOEVER, INCLUDING, BUT NOT LIMITED TO, DIRECT, INDIRECT, SPECIAL, PUNITIVE, EXEMPLARY, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, CONTRACT, NEGLIGENCE, TORT OR STRICT LIABILITY), INCLUDING, WITHOUT LIMITATION, LOSS OF GOODWILL, PROFITS OR DATA AND BUSINESS INTERRUPTION, ARISING HEREUNDER, RESULTING FROM OR ARISING OUT OF THE SITE, ANY COMMUNICATIONS AND INTERACTIONS OR MEETINGS WITH USERS OF THE SITE OR OTHER PERSONS WITH WHOM YOU COMMUNICATE AS A RESULT OF YOUR USE OF THE WEBSITE, AND/OR THE CONTENT, YOUR USE OR INABILITY TO USE THE SITE AND/OR THE CONTENT AND/OR THE FAILURE OF THE SITE TO PERFORM AS REPRESENTED OR EXPECTED, OR FROM ANY CONTENT, OR FROM THE PERFORMANCE OR FAILURE OF AUCTUS TO PERFORM UNDER THESE TERMS, ANY OTHER ACT OR OMISSION OF AUCTUS OR AUCTUS'S REPRESENTATIVES, OFFICERS, EMPLOYEES, AGENTS, CONTRACTORS, PARTNERS, ASSIGNEES BY ANY OTHER CAUSE WHATSOEVER; OR BASED UPON BREACH OF WARRANTY, GUARANTEE OR CONDITION, BREACH OF CONTRACT, NEGLIGENCE, STRICT LIABILITY, TORT, OR ANY OTHER LEGAL THEORY, REGARDLESS OF WHETHER AUCTUS OR AUCTUS'S REPRESENTATIVES, OFFICERS, EMPLOYEES, AGENTS, CONTRACTORS, PARTNERS, ASSIGNEES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <p>In any case, without limiting the generality of the foregoing and to the maximum extent legally permissible, Auctus’ and Auctus' representatives' total aggregate liability for all damages or losses whatsoever arising hereunder or in connection with your use or inability to use the Website and/or the content shall be limited to the amount actually paid by you, if any, to Auctus for use of the site or $1, whichever is greater. You will not, and hereby waive any right to, seek to recover any other damages, including consequential, lost profits, special, indirect or incidental damages from us and from Auctus' representatives, officers, employees, agents, contractors, partners, assignees. Inasmuch as some jurisdictions do not allow the exclusions or limitations as set forth herein, the full extent of the above exclusions and limitations may not apply.</p>
            <h3>13. INDEMNIFICATION</h3>
            <p>TO THE FULLEST EXTENT PERMITTED BY THE APPLICABLE LAW, YOU WILL INDEMNIFY, HOLD HARMLESS AND DEFEND AUCTUS, ITS OFFICERS, EMPLOYEES, AGENTS, CONSULTANTS, CONTRACTORS, SHAREHOLDERS, SERVICE PROVIDERS, AFFILIATES, REPRESENTATIVES, SUCCESSORS AND ASSIGNS FROM AND AGAINST ALL AND ANY DAMAGES, LIABILITIES, CLAIMS, LOSSES, COSTS, INCLUDING ATTORNEYS’ FEES THAT ARISE DIRECTLY OR INDIRECTLY FROM YOUR ACCESS OR USE OF THE WEBSITE, OUR SERVICES, YOUR USER GENERATED CONTENT AND VIOLATION OF THESE TERMS. WE RESERVE THE RIGHT TO EXERCISE SOLE CONTROL OVER THE DEFENSE, AT YOUR EXPENSE, OF ANY CLAIM SUBJECT TO INDEMNIFICATION PURSUANT TO THESE TERMS. THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF, ANY OTHER INDEMNITIES SET FORTH IN A WRITTEN CONTRACT BETWEEN YOU AND AUCTUS.  </p>
            <h3>14. MISCELLANEOUS </h3>
            <p>14.1 <span className="underline">Entire agreement</span>. These Terms contain the entire agreement, and supersede all prior and contemporaneous understandings between the parties regarding the subject matters hereof. These Terms do not alter the terms or conditions of any other electronic or written agreement you may have with Auctus for the terms of use for any other Auctus product or service or otherwise. In the event of any conflict between these Terms and any other agreement you may have with Auctus, the Terms of that other document will control only if these Terms are specifically identified and declared to be overridden by such other document.</p>
            <p>14.2 <span className="underline">Amendments</span>. Auctus may modify, change, supplement or update these Terms in our sole discretion at any time without advance notice. If we make changes to these Terms, we will provide you with notice of such changes, such as by sending an email, providing notice on the homepage of the Site and/or by posting the amended Terms via the applicable Website and updating the "Last Updated" date at the top of these Terms. The amended Terms will be deemed effective immediately upon posting for any new Users. In all other cases, the amended Terms will become effective for pre-existing Users upon the earlier of either: (i) the date Users click or press a button to accept such changes, or (ii) Users continued use of Website after Auctus provides notice of such changes. Any amended Terms will apply prospectively to use of the Terms after such changes become effective. If you do not agree to any amended Terms, you must immediately cease from using the Website.</p>
            <p>14.3 <span className="underline">Severability</span>. The invalidity or unenforceability of any of these Terms shall not affect the validity or enforceability of any other of these Terms, all of which shall remain in full force and effect.</p>
            <p>14.4 <span className="underline">Language</span>. Currently, only English versions of any Auctus’ communications are considered official. The English version shall prevail in case of differences in translation.</p>
            <p>14.5 <span className="underline">Force Majeure Events</span>. Auctus shall not be liable for (1) any inaccuracy, error, delay in, or omission of (i) any information, or (ii) the transmission or delivery of information; (2) any loss or damage arising from any event beyond Auctus' reasonable control, including but not limited to flood, extraordinary weather conditions, earthquake, or other act of God, fire, declared and undeclared war, insurrection, riot, labor dispute, accident, action of government, authorities, communications, power failure, or equipment or software malfunction or any other cause beyond Auctus’ reasonable control.</p>
            <p>14.6 <span className="underline">Assignment</span>. You may not assign or transfer any of your rights or obligations under these Terms without prior written consent from Auctus, including by operation of law or in connection with any change of control. Auctus may assign or transfer these Terms, any or all of its rights under these Terms, in whole or in part, without obtaining your consent or approval, provided that you will be informed of such transfer in the order provided herein.</p>
        </div>
        </div>)
    }
}
export default withRouter(Terms)