org: auctus
app: aco
service: aco

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  environment: ${ssm:/aws/reference/secretsmanager/aco/lambda/${opt:stage, self:provider.stage}.env.json~true}

functions:
  tokens:
    handler: handler.tokens
    timeout: 30
    events:
      - http:
          path: /tokens
          method: get
          cors: true
  pools:
    handler: handler.pools
    timeout: 30
    events:
      - http:
          path: /pools
          method: get
          cors: true
  poolHistoricalShares:
    handler: handler.poolHistoricalShares
    timeout: 30
    events:
      - http:
          path: /pools/{pool}/historical
          method: get
          cors: true
          request:
            parameters:
              paths:
                pool: true
  poolSituation:
    handler: handler.poolSituation
    timeout: 30
    events:
      - http:
          path: /pools/{pool}/status
          method: get
          cors: true
          request:
            parameters:
              paths:
                pool: true
  poolHistoricalEvents:
    handler: handler.poolHistoricalEvents
    timeout: 30
    events:
      - http:
          path: /pools/{pool}/events
          method: get
          cors: true
          request:
            parameters:
              paths:
                pool: true
  deribit:
    handler: handler.deribitTicker
    timeout: 30
    events:
      - http:
          path: /deribit/ticker
          method: get
          cors: true
  opynQuote:
    handler: handler.opynQuote
    timeout: 30
    events:
      - http:
          path: /opyn/quote
          method: get
          cors: true
  assets:
    handler: handler.assets
    timeout: 30
    events:
      - http:
          path: /assets
          method: get
          cors: true      
  getOrder:
    handler: handler.getOrder
    timeout: 30
    events:
      - http:
          path: /order/{orderId}
          method: get
          cors: true       
  createOrder:
    handler: handler.createOrder
    timeout: 30
    events:
      - http:
          path: /order
          method: post
          cors: true